job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/SenseiRofu/JenkinsStudy.git", 'main')
    }
    triggers {
        scm('1 * * * *')
    }
    steps {
        maven{
            goals('clean package')
            goals('build package')
            rootPOM('pom.xml')
            mavenInstallation('maven-3.8.6')
    post {
        success {
            echo "Now Archiving the Artifacts....."
            archiveArtifacts artifacts: '**/*.jar'
              }
        }
      
        
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
